### ISSUE TITLE
FRP: add a checkbox for every item ysync searchs for

### ISSUE THREAD

**Issue by 0xBasically** [yearn/ySync#105]
### What is your proposal 🚀
Add a checkbox to inculde exculde all itesm that are currently searched for. Every item should be toggleable off and on. Thus I can set it to only show vault icons errors, and also update the % complete to what is toggled out of all vaults, dont make it static for all items
![image](https://github.com/yearn/ySync/assets/131375535/5741af90-d5e6-4010-997f-847c2f68cddf)

- risk
- risk score
- apy
- price
- strategies
- ledger live
- ... ect

### What does this solve ? 🛠
We can search for only what our team wants to look at.

### More 🔎
*N/A*

**Comment by baibhavKumar1** [comment]
Hi @0xBasically , I want to contribute on the issue, please help me with design, where the checkboxes will be added .

**Comment by 0xBasically** [comment]
![image](https://github.com/yearn/ySync/assets/131375535/9d1d2903-4b1b-4ba6-b78c-f926fd214584)
maybe bring the version down a row, and add the checkbox on the same row as price/icon

**Comment by 0xBasically** [comment]
To get this working might need a refactor of the codebase though

**Comment by karelianpie** [comment]
@0xBasically removed the "good first issue" flag as this is definitely not trivial.

It would require quite a substancial refactoring, we need to rethink how these filters are working as how it currently stands it's a bit tricky to get all items with those filters

**Comment by karelianpie** [comment]
> and also update the % complete to what is toggled out of all vaults, dont make it static for all items

@0xBasically Let's tackle this in another issue; https://github.com/yearn/ySync/issues/109

Once the PR https://github.com/yearn/ySync/pull/108 to add all items is merged, I can try and tackle the error %
