### ISSUE TITLE
FRP: Add a check in Vaults tab for New APYs

### ISSUE THREAD

**Issue by DarkGhost7** [yearn/ySync#41]
Basically we set a new override if a vault has > 2 harvests. Or if it is a new vault and exporter is wrong when calculating apy for that vault, possibly like fetching token prices. This would be a check if a vault in meta data/vaults has "apyTypeOverride": "new", and is outputting an apy not error or > 0. This would help us catch cases where a new type is set and someone forget to check if it now has had 2 harvests.

**Comment by DarkGhost7** [comment]
**What is your proposal?**
For each vault that has NEW APY listed in meta [as seen here](https://github.com/yearn/ydaemon/blob/d1f9d619f84b1e5a89de2e120cb4a6c2a8206677/data/meta/vaults/1/0x1025b1641d1F23C289412Dd5E5701e9810103a93.json#L12) on the vault page under the vault, show category New and show this if Net APY > 0 or APY = error. Maybe show current APY and a link to the meta repo to fix it. If apy override = New & apy = 0 dont show anything.

**What does this solve?** 
This settings is manually and this would help show when it needs to be deleted to show apy. Generally this is for when a new vault hasn't yet harvest and apy is 0, so we add new.

**Comment by Majorfi** [comment]
Taking care of that in #68
