### ISSUE TITLE
FRP: Add links for icons with the addresses

### ISSUE THREAD

**Issue by DarkGhost7** [yearn/ySync#58]
### What is your proposal 🚀
on ySync 
![image](https://user-images.githubusercontent.com/38810205/188220744-93f6af7b-b707-4fd3-b422-5bae7963df6d.png)
add links for vault address under icon category: 
Icon KO for [vault](vaults address copyable here)
Icon KO for [underlying token](vault want token address copyable here)
### What does this solve ? 🛠
Makes adding icons to the yearn-asset repo easier.

**Comment by Majorfi** [comment]
Will be fixed in #68
