### ISSUE TITLE
FRP: Detect if a protocol file is missing in Strategy tab

### ISSUE THREAD

**Issue by karelianpie** [yearn/ySync#72]
### What is your proposal 🚀

Add error message when a protocol is listed on a strategy but doesn't have a protocol file, spin-off https://github.com/yearn/ySync/pull/71#issuecomment-1263842184

### What does this solve ? 🛠

Helps detect when a protocol does not even exist and is listed in a strategy

### More 🔎
*N/A*

**Comment by karelianpie** [comment]
@DarkGhost7 for this one we need to standardise the protocol filenames. I'd suggest we ignore all the special characters and compare them case-insensitive. Wdyt?

Another option is to add a `filename` prop to the protocol JSON, so https://github.com/yearn/yearn-meta/blob/master/data/protocols/1/CreamFinance.json would be

```json
{
  "$schema": "protocol",
  "name": "C.R.E.A.M. Finance",
  "description": "C.R.E.A.M. Finance is a decentralized lending protocol for individuals, institutions and protocols to access financial services. Part of the yearn.finance ecosystem, it is a permissionless, open source and blockchain agnostic protocol serving users on Ethereum, Binance Smart Chain and Fantom. Users can deposit their assets on C.R.E.A.M. to earn yield, similar to a traditional savings account.",
  "filename": "CreamFinance.json",
  "localization": {}
}
```

<img width="1151" alt="yearn-meta_CreamFinance_json_at_master_·_yearn_yearn-meta" src="https://user-images.githubusercontent.com/78794805/193591558-cdedbc94-cdf1-40f8-a771-721035c4ca43.png">

<img width="1017" alt="Screenshot_3_10_2022__4_40_pm" src="https://user-images.githubusercontent.com/78794805/193592030-b4e4f55f-6b47-4268-a209-14c21f2c656f.png">

**Comment by DarkGhost7** [comment]
Was cream the only protocol name giving this issue? Also I can see spaces being an issues as well

**Comment by karelianpie** [comment]
> Was cream the only protocol name giving this issue? Also I can see spaces being an issues as well

I didn't go through all the files, cream was the one that I know was for sure different. We should nonetheless try and make this future proof, I think removing the special characters (including spaces) and ignoring case should be enough. Then, we would catch the errors in the ySync repo anyways. Unsure if too much of an overhead to add a new `filename` prop. Wdyt?

**Comment by DarkGhost7** [comment]
If we did this all protocol name: field should be the same correct so all Curve Finance should turn into CurveFinance? I think it looks better with a space, but probably easier than making a new field if we want the .json name to match the protocol name

**Comment by karelianpie** [comment]
> If we did this all protocol name: field should be the same correct so all Curve Finance should turn into CurveFinance? I think it looks better with a space, but probably easier than making a new field if we want the .json name to match the protocol name

We don't need to change the actual protocol name, I can just remove the special chars before the comparison. I'll go ahead and implement the feature as discussed (removing specials chars and ignoring case) and we shall see if there's actually any protocol that has a file but the code is failing to find it. We can take it from there if there are any inconsistencies with filename and protocol name
