### ISSUE TITLE
FRP: Integrate the template settings page

### ISSUE THREAD

**Issue by Majorfi** [yearn/ySync#81]
### What is your proposal 🚀
We need to add a settings page (like web.ycorpo.com/settings), the one available in the template repo, to be able to overwrite some stuff, and mostly yDaemon Uri in case something is down!

The [`useSettings.tsx`](https://github.com/yearn/web-lib/blob/main/packages/web-lib/contexts/useSettings.tsx) exposes a bunch of functions to be able to overwrite the defaults settings used by the app.
Every app should use `useSettings` variables instead of local constants, variables or env.

For ex, the [`YDAEMON_ENDPOINT `](https://github.com/yearn/ySync/blob/next/next.config.js#L40) env variable should ne be used, but the [`yDaemonBaseURI`](https://github.com/yearn/web-lib/blob/4638bbd2a555059c74af9d23aafeeb6b7e5d31f7/packages/web-lib/contexts/useSettings.tsx#L11) should be used instead

### What does this solve ? 🛠
Provide a better **DE**fi and way to overwrite settings if our stuff are down

### More 🔎
*N/A*

**Comment by ai-slave** [comment]
So the job is:

- [ ] Create a way to show settings page to a user with an ability to override fields for this session
- [ ] Replace any hard-coded (env) variables across the project with ones from settings

If that's right – I can own this and other settings task.

**Comment by Majorfi** [comment]
Yes!
And the settings page already have a draft in the template repository. Worth checking and forking
