### ISSUE TITLE
FRP: add a check if a migration's vault was closed

### ISSUE THREAD

**Issue by DarkGhost7** [yearn/ySync#85]
### What is your proposal 🚀
Add a check if a vault's migration target vault is no longer live so the migration can be removed from meta.
example: https://github.com/yearn/ydaemon/blob/develop/data/meta/vaults/1/0x3B96d491f067912D18563d56858Ba7d6EC67a6fa.json#L14 is to this vault https://github.com/yearn/ydaemon/blob/develop/data/meta/vaults/1/0x8cdf57760Be305F32e03B3d231e5A81e550C6295.json which has deposits=disabled and deposit limit is 0.

### What does this solve ? 🛠
We have live migrations in meta that will fail to go through. 

### More 🔎
*N/A*

**Comment by karelianpie** [comment]
@Majorfi will add this data in yDaemon. Once we have it we can revisit this.

**Comment by DarkGhost7** [comment]
sounds good

**Comment by karelianpie** [comment]
@Majorfi any updates here?

**Comment by Majorfi** [comment]
Closed, provided a process on yDaemon only
