### ISSUE TITLE
FRP: on apy error check if vault is retired

### ISSUE THREAD

**Issue by 0xBasically** [yearn/ySync#90]
### What is your proposal 🚀
when searching for APY errors check first if vault in meta retired=true or hideAlways=true if either of those are true skip checking for APY since it doesnt matter

### What does this solve ? 🛠
We dont want old vaults showing an apy error

**Comment by karelianpie** [comment]
@0xBasically is this still on hold?

**Comment by 0xBasically** [comment]
No it should be able to be worked on
