### ISSUE TITLE
FRP: Make a toggle for Icon image errors

### ISSUE THREAD

**Issue by 0xBasically** [yearn/ySync#92]
### What is your proposal 🚀

Icon toggle (such as the one for missing translations) enabled by default to show/hide the **icon** section

If not too much work, another toggle for the **price** section

### What does this solve ? 🛠

Images and meta updates are updated differently in different repos so seeing them one at a time is cleaner, or the option to toggle one is nice. 

### More 🔎
*N/A*

**Comment by karelianpie** [comment]
@0xBasically do you mean a toggle for the icons?

**Comment by 0xBasically** [comment]
Yes that is what I mean
